version: "3"

services:

  app_service:
    image: app
    ports:
      - "80:80"
    deploy:
      replicas: 4
    networks:
      - network_swarm_service

  db_service:
    image: database
    environment:
      MYSQL_ROOT_PASSWORD: root1
    deploy:
      replicas: 1
    ports:
      - "3306:3306"
    networks:
      - network_swarm_service

  rest_service:
    image: rest
    deploy:
      replicas: 1
    command: >
      sh -c "while ! nc -z db_service 3306; do sleep 1; done; npm start"
    ports:
      - "8080:8080"
    networks:
      - network_swarm_service

  soap_service:
    image: soap
    deploy:
      replicas: 1
    command: >
      sh -c "while ! nc -z db_service 3306; do sleep 1; done; npm start"
    ports:
      - "8888:8888"
    networks:
      - network_swarm_service

networks:
  network_swarm_service:
